services:
  api:
    build: ./api
    ports:  
        - 3000:3000
  prometheus:
    image: prom/prometheus
    volumes:
        - ./prometheus:/etc/prometheus
        - prometheus:/prometheus
    command:
        - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 7000:3000
    
volumes:
  prometheus: